version: '3'

services:
  movies:
    build: ./services/movies
    ports:
      - "4001:3001"
  tv:
    build: ./services/tv_series
    ports:
      - "4002:3002"
  orchestrator:
    build: ./orchestrator
    ports:
      - "4000:3000"
  mongo:
    image: "mongo"
    ports:
      - "37017:27017"
    command: mongod